CREATE TABLE product (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  type ENUM('book', 'dvd', 'furniture') NOT NULL,
  created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) DEFAUlT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);

CREATE TABLE dvd (
  id INT AUTO_INCREMENT PRIMARY KEY,
  size DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (id) REFERENCES product(id) ON DELETE CASCADE
);

CREATE TABLE book (
  id INT AUTO_INCREMENT PRIMARY KEY,
  weight DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (id) REFERENCES product(id) ON DELETE CASCADE
);

CREATE TABLE furniture (
  id INT AUTO_INCREMENT PRIMARY KEY,
  height DECIMAL(10, 2) NOT NULL,
  width DECIMAL(10, 2) NOT NULL,
  length DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (id) REFERENCES product(id) ON DELETE CASCADE
);
